### ISSUE TITLE
Rate limit reached due to `GITHUB_TOKEN` not being read

### ISSUE THREAD

**Issue by nickelghost** [editorconfig-checker/editorconfig-checker.javascript#425]
Hi there, we just ran into the rate limit ssue.
```
Failed to download binary:
HttpError: API rate limit exceeded for <REDACTED> (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```
We tried adding a `GITHUB_TOKEN` environment variable, but it wasn't read.

**Comment by chrisopperwall-qz** [comment]
Hello! Sorry for bumping this issue, I can totally start a new thread, but I've come across similar rate limit issues in my CI due to being unauthenticated. I'm currently on v6.1.0, so I'm on the latest version. I was looking at the docs for the Octokit constructor in `@octokit/rest` and it looks like it [re-exports](https://github.com/octokit/rest.js/blob/main/src/index.ts#L1) the constructor from `@octokit/core`. I found some comments in the constructor in that package that say that if `auth` or `authStrategy` are not set then requests will continue unauthenticated https://github.com/octokit/core.js/blob/main/src/index.ts#L155.

It looks like `@octokit/action` has some built-in features to look for GITHUB_TOKEN via the `@octokit/auth-action` package here https://github.com/octokit/action.js/blob/main/src/index.ts#L16, whereas the `@octokit/rest` version expects auth information to be passed explicitly.

I made a [fork](https://github.com/chrisopperwall-qz/editorconfig-checker.javascript/commit/c2385ea28ffe8adf000aa73004d2f151a1f56566) that passes the token explicitly, but I wanted to check first if that approach seemed okay. Thanks for maintaining this!

**Comment by mstruebing** [comment]
If you can't find any other way, please open a PR to adjust our call side :)
