### ISSUE TITLE
Is it possible to distinguish indentation and alignment?

### ISSUE THREAD

**Issue by okalachev** [editorconfig-checker/editorconfig-checker.javascript#68]
Here is a part of C++ code:

<img width="745" alt="Screenshot 2019-07-09 at 06 10 32" src="https://user-images.githubusercontent.com/1683279/60856560-4312e900-a210-11e9-8aea-8110bdacf21c.png">

It uses tabs for the indentation (`indent_style = tab` in `.editorconfig`) and uses spaces to align the second line of arguments with the opening bracket.

`editorconfig-checker` finds an error here:

```
136: Wrong indentation type(spaces instead of tabs)
```

Is it possible to avoid it?

**Comment by mstruebing** [comment]
Hey @okalachev, 
Thanks for your question but unfortunately the editorconfig-specification doesn't have a way to distinguish between indentation and alignment, therefore I will not implement this.

What you could do in order to get rid of the errors is writing `editorconfig-disable-line` at the end of your line (in a comment ofc). see: https://github.com/editorconfig-checker/editorconfig-checker#excluding-lines

That would work, but I would argue if you should have different indentation-types inside a single file, that doesn't make much sense in my honest opinion.

If your question is answered and clear now, please feel free to close this issue.

**Comment by okalachev** [comment]
@mstruebing 

>That would work, but I would argue if you should have different indentation-types inside a single file, that doesn't make much sense in my honest opinion.

For me, it's the best way to go. We use tabs for indentation, so everyone can adjust the tab size for their taste. But we use spaces for indentation, so any tab size would not break it.

It's too bad, that it's not supported by `.editorconfig`.

**Comment by okalachev** [comment]
@mstruebing, wouldn’t it be better, if the checker could detect the alignment with spaces?
If there are spaces afters tabs, then they are likely to be alignment, not indentation.

**Comment by mstruebing** [comment]
Hey, thanks again for trying to make the tool better :)
Is this a common pattern to do (spaces after tabs for alignment)?
Can you provide any sources that people are doing it except yourself or your company?

If that is the case, I would be willing to implement this

**Comment by okalachev** [comment]
@mstruebing, yeah, that's a lot of sources: https://dmitryfrank.com/articles/indent_with_tabs_align_with_spaces, https://vim.fandom.com/wiki/Indent_with_tabs,_align_with_spaces, https://www.freecodecamp.org/forum/t/styling-tip-tabs-for-indentation-spaces-for-alignment/163469, https://marketplace.visualstudio.com/items?itemName=j-zeppenfeld.tab-indent-space-align.

This option is called "Smart tabs" in popular JetBrains IDEs: https://www.jetbrains.com/help/phpstorm/settings-code-style-tabs-and-indents-common.html#f2a9d78e.

You can google "tabs for indentation spaces for alignment" to find more.

**Comment by mstruebing** [comment]
Thank you, sorry I didn't know this is a common pattern.

Could you open a detailed issue how you imagine it to work (especially in edge cases if there are any) here: https://github.com/editorconfig-checker/editorconfig-checker/issues/new

That would be great :+1:
